// Command raylibfont decodes raylib's default font from raylib's rtext.c
// and writes it as Go glyph rows ('#'/'.') for the ui:
//
//	go run ./internal/tools/raylibfont path/to/rtext.c > ui/fonts/raylib.go
//
// raylib is zlib/libpng licensed, Copyright (c) 2013-2026 Ramon Santamaria
// (@raysan5); the generated file carries that notice.
package main

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: raylibfont rtext.c")
		os.Exit(2)
	}
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	s := string(src)
	data := numbers(block(s, "unsigned int defaultFontData[512] = {"))
	widths := numbers(block(s, "int charsWidth[224] = {"))
	if len(data) != 512 || len(widths) != 224 {
		fmt.Fprintf(os.Stderr, "unexpected sizes: %d data words, %d widths\n", len(data), len(widths))
		os.Exit(1)
	}

	// The 128x128 one-bit sheet: pixel p is bit p%32 of word p/32.
	const size, height, divisor = 128, 10, 1
	on := func(x, y int) bool {
		p := y*size + x
		return data[p/32]>>(p%32)&1 != 0
	}

	var b strings.Builder
	b.WriteString(`// Code generated by internal/tools/raylibfont from raylib's rtext.c. DO NOT EDIT.

// raylib's default font. raylib is licensed under the zlib/libpng license:
// Copyright (c) 2013-2026 Ramon Santamaria (@raysan5). This software is
// provided 'as-is', without any express or implied warranty. Permission is
// granted to anyone to use it for any purpose, including commercial
// applications, and to alter it and redistribute it freely, subject to: the
// origin must not be misrepresented; altered versions must be plainly marked
// as such; this notice may not be removed or altered from any distribution.

package fonts

// Raylib is raylib's default font: 10 pixels high, glyphs for runes 32 to
// 255, drawn with 1 pixel between glyphs.
var Raylib = Bitmap{
	Name:    "raylib",
	Height:  10,
	Spacing: 1,
	Glyphs: map[rune][]string{
`)
	// Glyph rectangles, exactly as raylib's LoadFontDefault cuts them.
	line, posX, testX := 0, divisor, divisor
	for i := range 224 {
		w := int(widths[i])
		x, y := posX, divisor+line*(height+divisor)
		testX += w + divisor
		if testX >= size {
			line++
			posX = 2*divisor + w
			testX = posX
			x, y = divisor, divisor+line*(height+divisor)
		} else {
			posX = testX
		}
		r := rune(32 + i)
		fmt.Fprintf(&b, "\t\t%d: { // %q\n", r, r)
		for dy := range height {
			var row strings.Builder
			for dx := range w {
				if on(x+dx, y+dy) {
					row.WriteByte('#')
				} else {
					row.WriteByte('.')
				}
			}
			fmt.Fprintf(&b, "\t\t\t%q,\n", row.String())
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t},\n}\n")
	fmt.Print(b.String())
}

// block returns the text between the given opening and the next "}".
func block(s, open string) string {
	i := strings.Index(s, open)
	if i < 0 {
		return ""
	}
	s = s[i+len(open):]
	return s[:strings.Index(s, "}")]
}

var number = regexp.MustCompile(`0x[0-9a-fA-F]+|\d+`)

func numbers(s string) []uint32 {
	var out []uint32
	for _, m := range number.FindAllString(s, -1) {
		v, err := strconv.ParseUint(m, 0, 32)
		if err != nil {
			continue
		}
		out = append(out, uint32(v))
	}
	return out
}
